"""empty message

Revision ID: f58cbde210af
Revises: b063b64ae171
Create Date: 2017-08-11 09:18:39.806503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58cbde210af'
down_revision = 'b063b64ae171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'entry', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'entry', type_='foreignkey')
    # op.drop_column('entry', 'author_id')
    # ### end Alembic commands ###
